version: "3.3"

services:

  web:
    restart: unless-stopped
    build: web
    ports:
      - 8889:80

  # auth:
  #   restart: unless-stopped
  #   image: "eo:build"

  # eo:
  #   restart: unless-stopped
  #   image: "eo:build"
  #   depends_on:
  #     - auth  # MUST have auth up first otherwise potential map corruption
