version: "3.3"

services:

  web:
    restart: unless-stopped
    build: web
    ports:
      - 8889:80

  auth:
    restart: unless-stopped
    build: auth
    ports:
      # TODO: Flask config only binds to localhost, so this is not exposed properly.
      - 5000:5000
    volumes:
      # TODO: This should be templated with env vars
      - ./outpost_auth.ini:/eo-auth/outpost_auth.ini:ro

  # eo:
  #   restart: unless-stopped
  #   image: "eo:build"
  #   depends_on:
  #     - auth  # MUST have auth up first otherwise potential map corruption
